Feature plugin unloading
TeamWisp/Maya-Ray-Traced-Viewport-Plugin pull request #76
Opened 2019-05-21 12:25 UTC by tntmeijs

The plug-in would still crash even though "PostQuitMessage(0)" had already been removed in Wisp. These changes will make sure all objects in the plug-in will be deallocated properly as well.

This fixes #4 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2019-05-23 08:12 UTC, sainsay requested changes
one small code change required.
Wisp library is pointing to a different branch than master. please wait/ update to wisp master branch when required pull request has been merged

2019-05-23 08:12 UTC, sainsay commented on src/plugin/renderer/renderer.cpp
> +#include <maya/M3dView.h>
not needed include

2019-05-23 11:44 UTC, MeineZ commented on module/wisp/bin/resources/shaders/deferred_composition.hlsl
> +		ao *= gbuffer_ao;
Duplicated multiplication? Probably due to wisp already being updated in the latest plugin version?

2019-05-23 11:44 UTC, MeineZ commented on src/plugin/renderer/material_manager.cpp
> +	const auto& renderer = dynamic_cast<const ViewportRendererOverride*>(MHWRender::MRenderer::theRenderer()->findRenderOverride(settings::VIEWPORT_OVERRIDE_NAME))->GetRenderer();
`LOG` is removed intentionally?

2019-05-23 11:45 UTC, tntmeijs commented on src/plugin/renderer/material_manager.cpp
> +	const auto& renderer = dynamic_cast<const ViewportRendererOverride*>(MHWRender::MRenderer::theRenderer()->findRenderOverride(settings::VIEWPORT_OVERRIDE_NAME))->GetRenderer();
Yes.

2019-05-27 14:36 UTC, MeineZ approved these changes
Works fine now! 👍

2019-05-27 14:56 UTC, sainsay approved these changes

2019-05-27 14:56 UTC, merged